addressbook/urls.py
from django.urls import path

from addressbook.views import (
    LoginView,
    LogoutView,
    RecordCreateView,
    RecordDeleteView,
    RecordDetailView,
    RecordsIndexView,
    RecordUpdateView,
)

app_name = "addressbook"
urlpatterns = [
    path("", RecordsIndexView.as_view(), name="index"),
    path("record/<int:pk>", RecordDetailView.as_view(), name="detail"),
    path("create", RecordCreateView.as_view(), name="create"),
    path("update_record/<int:pk>", RecordUpdateView.as_view(), name="update"),
    path("delete_record/<int:pk>", RecordDeleteView.as_view(), name="delete"),
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("address_book/", include("addressbook.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

addressbook/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class TimestampModel(models.Model):
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("modified at"), auto_now=True)

    class Meta:
        abstract = True


class BookRecord(TimestampModel):
    first_name = models.CharField(verbose_name="first name", max_length=30, null=True, blank=True)
    last_name = models.CharField(verbose_name="last name", max_length=50, null=True, blank=True)
    name = models.CharField(verbose_name="name", max_length=50, null=True, blank=True)
    image = models.ImageField(upload_to="images/", blank=True, null=True)

    city = models.CharField(verbose_name=_("city"), max_length=50, null=False, blank=False)
    post_code = models.CharField(
        verbose_name=_("post code"),
        max_length=6,
        null=False,
        blank=False,
    )
    building_number = models.CharField(verbose_name=_("building number"), max_length=5, null=False, blank=False)
    local_number = models.CharField(verbose_name=_("local number"), max_length=5, null=False, blank=False)

    class Meta:
        verbose_name = _("book record")
        verbose_name_plural = _("book records")

    def __str__(self):
        return f"{self.first_name} {self.last_name}" if self.first_name or self.last_name else f"{self.name}"


class Phone(TimestampModel):
    phone = PhoneNumberField(verbose_name="phone", null=False, blank=False)
    address_record = models.ForeignKey(
        BookRecord,
        verbose_name=_("address record"),
        on_delete=models.CASCADE,
        related_name="phones",
        null=True,
    )

    class Meta:
        verbose_name = _("phone")
        verbose_name_plural = _("phones")

    def __str__(self):
        return f"{self.phone}"


class Fax(TimestampModel):
    fax = models.CharField(
        verbose_name="fax",
        max_length=12,
        null=False,
        blank=False,
        validators=[
            RegexValidator(
                regex=r"^\+?[0-9]{6,}$",
                message=_("Invalid fax number, eg. +123456"),
            ),
        ],
    )
    address_record = models.ForeignKey(
        BookRecord,
        verbose_name=_("address record"),
        on_delete=models.CASCADE,
        related_name="faxes",
        null=True,
    )

    class Meta:
        verbose_name = _("fax")
        verbose_name_plural = _("fax numbers")

    def __str__(self):
        return f"{self.fax}"


class Email(TimestampModel):
    email = models.EmailField(verbose_name="email", max_length=100, blank=True, null=True)
    address_record = models.ForeignKey(
        BookRecord,
        verbose_name=_("address record"),
        on_delete=models.CASCADE,
        related_name="emails",
        null=True,
    )

    class Meta:
        verbose_name = _("email")
        verbose_name_plural = _("emails")

    def __str__(self):
        return f"{self.email}"

addressbook/forms.py
from django import forms
from django.utils.translation import gettext

from addressbook.models import BookRecord


class AddressBookForm(forms.ModelForm):
    id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    first_name = forms.CharField(required=False, max_length=30)
    last_name = forms.CharField(required=False, max_length=50)
    name = forms.CharField(required=False, max_length=50)
    image = forms.ImageField(required=False)
    city = forms.CharField(required=True, max_length=50)
    post_code = forms.CharField(required=True, max_length=6)
    building_number = forms.CharField(required=True, max_length=5)
    local_number = forms.CharField(required=False, max_length=5)

    def clean(self):
        super().clean()
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        name = self.cleaned_data.get("name")
        if not (first_name or last_name or name):
            raise forms.ValidationError({"name": gettext("at least one name field is required")})

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name and BookRecord.objects.filter(name=name).exists():
            raise forms.ValidationError(gettext("That name is already taken"))

    class Meta:
        model = BookRecord
        fields = "__all__"

addressbook/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.forms import inlineformset_factory, model_to_dict
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView

from addressbook.forms import AddressBookForm
from addressbook.models import BookRecord, Email, Fax, Phone


class RecordsIndexView(LoginRequiredMixin, ListView):
    template_name = "records/index.html"
    context_object_name = "book_records"

    def get_queryset(self):
        query_params = self.request.GET.get("q", "").lower()
        filters = Q()
        if query_params:
            filters |= Q(**{"first_name__iexact": query_params})
            filters |= Q(**{"last_name__iexact": query_params})

        return BookRecord.objects.filter(filters).order_by("-created_at")


EmailFormset = inlineformset_factory(
    BookRecord,
    Email,
    fields=["email"],
    can_delete_extra=False,
)
FaxFormset = inlineformset_factory(
    BookRecord,
    Fax,
    fields=["fax"],
    can_delete_extra=False,
)
PhoneFormset = inlineformset_factory(
    BookRecord,
    Phone,
    fields=["phone"],
    can_delete_extra=False,
)


class RecordDetailView(LoginRequiredMixin, DetailView):
    model = BookRecord
    template_name = "records/detail.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        form_object = AddressBookForm(data=model_to_dict(self.object))
        context["form_object"] = form_object
        context["image"] = self.object.image
        return self.render_to_response(context)


class RecordCreateView(LoginRequiredMixin, CreateView):
    form_class = AddressBookForm
    template_name = "records/create.html"
    success_url = "success"

    def post(self, request, *args, **kwargs):
        self.object = None
        emails = EmailFormset(request.POST)
        faxes = FaxFormset(request.POST)
        phones = PhoneFormset(request.POST)
        book_record_form = AddressBookForm(request.POST, request.FILES)
        if (emails.is_valid() and faxes.is_valid() and phones.is_valid()) and book_record_form.is_valid():
            return self.form_valid(book_record_form)
        return self.form_invalid(book_record_form)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["emails"] = EmailFormset(self.request.POST)
            data["faxes"] = FaxFormset(self.request.POST)
            data["phones"] = PhoneFormset(self.request.POST)
        else:
            data["emails"] = EmailFormset()
            data["faxes"] = FaxFormset()
            data["phones"] = PhoneFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        emails = context["emails"]
        faxes = context["faxes"]
        phones = context["phones"]

        self.object = form.save()

        self.create_objects(emails)
        self.create_objects(faxes)
        self.create_objects(phones)

        return super().form_valid(form)

    def create_objects(self, model):
        if model.is_valid():
            model.instance = self.object
            model.save()

    def get_success_url(self):
        return reverse("addressbook:index")


class RecordUpdateView(LoginRequiredMixin, UpdateView):
    model = BookRecord
    form_class = AddressBookForm
    template_name = "records/update.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        emails = EmailFormset(request.POST, instance=self.object)
        faxes = FaxFormset(request.POST, instance=self.object)
        phones = PhoneFormset(request.POST, instance=self.object)
        form = self.get_form()
        if (emails.is_valid() and faxes.is_valid() and phones.is_valid()) and form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["emails"] = EmailFormset(self.request.POST, instance=self.object)
            data["faxes"] = FaxFormset(self.request.POST, instance=self.object)
            data["phones"] = PhoneFormset(self.request.POST, instance=self.object)
        else:
            data["emails"] = EmailFormset(instance=self.object)
            data["faxes"] = FaxFormset(instance=self.object)
            data["phones"] = PhoneFormset(instance=self.object)

        if data["form"].is_valid():
            data["form"] = self.form_class(self.request.FILES, instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        emails = context["emails"]
        faxes = context["faxes"]
        phones = context["phones"]
        self.object = form.save()

        self.update_objects(emails)
        self.update_objects(faxes)
        self.update_objects(phones)

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("addressbook:index")

    def update_objects(self, model):
        if model.is_valid():
            model.instance = self.object
            model.save()


class RecordDeleteView(LoginRequiredMixin, DeleteView):
    model = BookRecord
    template_name = "records/delete.html"

    def get_success_url(self):
        return reverse("addressbook:index")


class LoginView(TemplateView):
    template_name = "records/login.html"

    def post(self, request, *args, **kwargs):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(self.get_redirect_url())
        else:
            messages.error(request, gettext("There was an error, try again..."))
            return HttpResponseRedirect(self.get_redirect_url())

    @staticmethod
    def get_redirect_url():
        return reverse("addressbook:index")


class LogoutView(View):
    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(self.get_success_url())

    @staticmethod
    def get_success_url():
        return reverse("addressbook:index")

addressbook/templates/records/create.html
{% include 'base.html' %}
<form method="post" enctype='multipart/form-data'>{% csrf_token %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-4">
                {% if form.errors %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                {% for field in form %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label }} : {{ field }}
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-3">
                <h2>Emails</h2>
                {{ emails.as_p }}
            </div>
            <div class="col-md-3">
                <h2>Faxes</h2>
                {{ faxes.as_p }}
            </div>
            <div class="col-md-2">
                <h2>Phones</h2>
                {{ phones.as_p }}
            </div>

        </div>
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <input type="submit" value="Save">
            </div>
        </div>
    </div>
</form>

    <a href="{% url 'addressbook:index' %}">Go back</a>

addressbook/templates/records/delete.html
{% include 'base.html' %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

addressbook/templates/records/detail.html
{% include 'base.html' %}
<h1>{{ bookrecord }}</h1>
<ul>
    {% for field in form_object %}
        {% if field.label == "Image" and image.url %}
            <p><img src="{{ image.url }}" width="300px" alt="mocked image"></p>
        {% else %}
        <li><b>{{ field.label }} </b>: {{ field.data }}</li>
        {% endif %}
    {% endfor %}

    {% if bookrecord.phones.exists %}
        <li><b>phones:</b>
            {% for phone in bookrecord.phones.all %}
                {{ phone }},
            {% endfor %}
        </li>
    {% endif %}

    {% if bookrecord.faxes.exists %}
        <li><b>faxes:</b>
            {% for fax in bookrecord.faxes.all %}
                {{ fax }},
            {% endfor %}
        </li>
    {% endif %}
    {% if bookrecord.emails.exists %}
        <li><b>emails:</b>
            {% for email in bookrecord.emails.all %}
                {{ email }},
            {% endfor %}
        </li>
    {% endif %}

</ul>
<ul>
    <a href="{% url 'addressbook:update' bookrecord.id %}">Update record</a>
</ul>
<ul>
    <a href="{% url 'addressbook:delete' bookrecord.id %}">DELETE record</a>
</ul>
<a href="{% url 'addressbook:index' %}">Back to list</a>

addressbook/templates/records/index.html
{% include 'base.html' %}

{% if book_records %}

    <form action="{% url 'addressbook:index' %}" method="get">
        <div class="d-flex flex-row">

            <input name="q" type="text" placeholder="first or last name">
            <div class="col-md-6 ">
                <input type="submit" value="Search">
            </div>
        </div>

    </form>
    <ul>
        {% for record in book_records %}
            <li><a href="{% url 'addressbook:detail' record.id %}">{{ record }}</a></li>    {% endfor %}
    </ul>
{% else %}
    <p>Address book is empty.</p>
    <p> Add something! </p>

{% endif %}
<a href="{% url 'addressbook:create' %}">Add new record</a>

addressbook/templates/records/login.html
{% include 'base.html' %}
<h1>Login</h1>

<form method="post">{% csrf_token %}
     <form action="/action_page.php">
  <div class="form-group">
    <label for="username">Username:</label>
    <input type="text" class="form-control" name="username" placeholder="Enter username" id="username">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" class="form-control" placeholder="Enter password" id="pwd" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</form>

addressbook/templates/records/update.html
{% include 'base.html' %}
<form method="post" enctype='multipart/form-data'>{% csrf_token %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-6">
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
                {% for field in form %}
                    <div class="form-group">
                    {% if field.errors %}
                        <div class="alert alert-danger">
                        {{ field.errors }}
                        </div>
                    {% endif %}
                    {{ field.label }} : {{ field }}
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-2">
                <h2>Emails</h2>
                {{ emails.as_p }}
            </div>
            <div class="col-md-2">
                <h2>Faxes</h2>
                {{ faxes.as_p }}
            </div>
            <div class="col-md-2">
                <h2>Phones</h2>
                {{ phones.as_p }}
            </div>
            <input type="submit" value="Save">
        </div>
    </div>
</form>